export const GET_LIST_MOVIE = "GET_LIST_MOVIE";
export const GET_DETAIL_MOVIE = "GET_DETAIL_MOVIE";
export const GET_LIST_CHAIR_BOOKING = "GET_LIST_CHAIR_BOOKING";

export const GET_LIST_USER = "GET_LIST_USER";
export const POST_DETAIL_USER = "POST_DETAIL_USER";
